### PR TITLE
Zero-cost JSX3/hooks compatible bindings.

### PR DESCRIPTION
**Pull request by cknitt**
@alexfedoseev As discussed on Discord, here is my take on zero-cost, JSX3 compatible bindings.

I just replaced ReactIntl.re with what I use in my current project, the examples won't build at the moment.

### CODE REVIEW

**Comment by alex35mil** [comment]
This looks great! I'm going to apply it to codebase and then merge. Thanks!

**Comment by dfalling** [comment]
DefinedMessage was dropped in this PR, is that a deliberate decision?  I make a lot of use of that in my project.

**Comment by cknitt** [comment]
This PR does not include `DefinedMessage` because my aim with these bindings was to match 1:1 to the JS API and to be zero cost. (Also, I do not use `DefinedMessage` in my projects.)

`DefinedMessage` is quite trivial to add, however. I think it should go into a separate module though (`ReactIntlExt`or whatever), as it has no direct correspondence in the JS API.

**Comment by alex35mil** [comment]
Agreed 👍 

I updated the app to the new bindings and it works great. `react-intl@3` beta was released but w/o a `useIntl` hook yet. Merging this into `hooks` branch but I want to wait a bit for official `react-intl@3` release (hope it'll be with `useIntl` hook).

**Pull request merged**
